### ISSUE TITLE
v1.2 broke Plots.jl CI

### ISSUE THREAD

**Issue by simeonschaub** [julia-actions/cache#42] opened 2023-01-07 14:14 UTC
Plots.jl CI started erroring with the following logs since the new release: https://github.com/JuliaPlots/Plots.jl/actions/runs/3859523069/jobs/6579133683#step:10:62. My initial suspicion came from a new environment variable `PRECOMPILATION_CACHE_PATH` appearing in CI logs, so maybe that has something to with the failures. Just downgrading the cache version to v1.1.7 did not fix the issue, probably because it was still using old cache files. For now, removing the caching step seems to work around the issue. (Ref https://github.com/JuliaPlots/Plots.jl/pull/4624)

**Comment by giordano** [comment] 2023-01-07 14:16
Repo maintainers can cleanup CI cache at https://github.com/JuliaPlots/Plots.jl/actions/caches, but being sensitive to an environment variable called `<WHATEVER>_PATH` sounds like a problem in Plots CI

**Comment by simeonschaub** [comment] 2023-01-07 14:24
I'm not familiar enough with Plots CI, but IIUC v1.2 only added a new option that's turned off by default, so it seems odd the new version broke this

**Comment by rikhuijzer** [comment] 2023-01-07 15:41
Duplicate of https://github.com/julia-actions/cache/issues/10.

Sounds like a Conda.jl bug since it is also an issue if you would move the Julia directory from one system to the next.

**Comment by t-bltg** [comment] 2023-01-07 16:40
FYI, we don't use `Conda.jl` but `CondaPkg.jl` in Plots (since the `pyplot` -> `pythonplot` transition). Looks like cleaning up the actions cache files fixed Plots CI.

**Comment by SaschaMann** [comment] 2023-01-07 19:20
I'll close it since it doesn't look like we can do anything on the side of this action and it appears to be a duplicate of #10. 

Feel free to reopen if you have a suggestion for something we can do, though.

**Closed by SaschaMann** 2023-01-07 19:20 UTC

**Comment by timholy** [comment] 2023-01-13 10:00
I'm not familiar with how this works here, but if there's any chance that the cached precompile files might get out-of-sync with the settings used for precompilation in the rest of the project, that could be a concern. ENV variables can cause subtle problems, see see https://github.com/MakieOrg/Makie.jl/issues/2585#issuecomment-1381567065.

**Comment by SaschaMann** [comment] 2023-01-13 13:10
The precompiled files aren't cached by default and the env vars shouldn't be accessed during compile time but we can take two precautions:

- Actually test that compiled isn't cached (#49)
- Use outputs instead of environment variables inside the action; that removes any potential interference even if it shouldn't matter (#48)
